spring:
  application:
    name: zoom-platform-server
  profiles:
    default: local
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: '@project.version@'

logging:
  pattern:
    correlation: '[%X{traceId:-}] '
